set positional-arguments

# Display help
help:
    just -l

# `osmiflow`
alias c := osmiflow
osmiflow *args:
    cargo run --bin osmiflow -- "$@"

# `osmiflow exec`
exec *args:
    cargo run --bin osmiflow -- exec "$@"

# `osmiflow tui`
tui *args:
    cargo run --bin osmiflow -- tui "$@"

# Run the CLI version of the file-search crate.
file-search *args:
    cargo run --bin codex-file-search -- "$@"

# format code
fmt:
    cargo fmt -- --config imports_granularity=Item

fix *args:
    cargo clippy --fix --all-features --tests --allow-dirty "$@"

clippy:
    cargo clippy --all-features --tests "$@"

install:
    rustup show active-toolchain
    cargo fetch

# Run `cargo nextest` since it's faster than `cargo test`, though including
# --no-fail-fast is important to ensure all tests are run.
#
# Run `cargo install cargo-nextest` if you don't have it installed.
test:
    cargo nextest run --no-fail-fast

# Run the MCP server
mcp-server-run *args:
    cargo run -p codex-mcp-server -- "$@"
